<#
    Installer answer file generation (debian-installer family).

    Every question the installer can ask must be answered here. A single missing
    key turns an unattended install into a machine sitting on a blue dialog with
    no one watching, which from the host looks identical to a hang.
#>

function New-AutoVMPreseed {
    <#
        .SYNOPSIS
        Renders a debian-installer preseed for a plan and a credential plan.

        .DESCRIPTION
        The late_command block is what makes a capitalised login work: the
        account is created lowercase (the only form user-setup accepts), then
        renamed, with its home directory moved and ownership repaired. The
        primary group is deliberately left lowercase - renaming it as well
        cascades into /etc/group, /etc/gshadow, /etc/subuid, /etc/subgid and
        sudoers for no benefit.

        .PARAMETER Password
        The guest account password. Written in clear text into the returned
        string, because the installer format requires it; the caller is
        responsible for shredding the file it writes.
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param(
        [Parameter(Mandatory)][psobject]$Plan,
        [Parameter(Mandatory)][psobject]$Guest,
        [Parameter(Mandatory)][string]$UserName,
        [Parameter(Mandatory)][securestring]$Password,
        [string]$FullName,
        [string]$HostName = 'autovm',
        [switch]$AllowWeakPassword
    )

    $check = Test-AutoVMUserName -UserName $UserName
    if (-not $check.IsValid) { throw "Invalid guest login '$UserName': $($check.Reason)" }

    $installerName = $check.Normalised
    $needsRename = $check.RequiresRename
    $display = if ($FullName) { $FullName } else { $UserName }
    $plain = ConvertFrom-AutoVMSecureString -Secure $Password

    $packages = (@($Plan.Packages) -join ' ')
    $weak = if ($AllowWeakPassword) { 'true' } else { 'false' }

    $lateCommand = if ($needsRename) {
        @"
d-i preseed/late_command string \
  in-target sh -c 'usermod --badname -l $UserName $installerName \
    || (sed -i "s/^${installerName}:/${UserName}:/" /etc/passwd /etc/shadow)' ; \
  in-target sh -c 'usermod --badname -d /home/$UserName -m $UserName \
    || (mv /home/$installerName /home/$UserName; sed -i "s#:/home/${installerName}:#:/home/${UserName}:#" /etc/passwd)' ; \
  in-target chown -R ${UserName}:${installerName} /home/$UserName ; \
  in-target sh -c 'echo "$UserName ALL=(ALL:ALL) ALL" > /etc/sudoers.d/autovm-user; chmod 440 /etc/sudoers.d/autovm-user' ; \
  in-target sh -c 'id $UserName > /var/log/autovm-account.log 2>&1'
"@
    } else {
        @"
d-i preseed/late_command string \
  in-target sh -c 'echo "$UserName ALL=(ALL:ALL) ALL" > /etc/sudoers.d/autovm-user; chmod 440 /etc/sudoers.d/autovm-user' ; \
  in-target sh -c 'id $UserName > /var/log/autovm-account.log 2>&1'
"@
    }

    $text = @"
# Generated by AutoVM. Contains the guest account password in clear text;
# this file is overwritten and deleted as soon as the install has consumed it.

d-i debian-installer/locale             string en_US.UTF-8
d-i keyboard-configuration/xkb-keymap   select us
d-i netcfg/choose_interface             select auto
d-i netcfg/get_hostname                 string $HostName
d-i netcfg/get_domain                   string local
d-i netcfg/hostname                     string $HostName

d-i mirror/country                      string manual
d-i mirror/http/hostname                string $($Guest.mirrorHostname)
d-i mirror/http/directory               string $($Guest.mirrorDirectory)
d-i mirror/http/proxy                   string

d-i clock-setup/utc                     boolean true
d-i time/zone                           string UTC
d-i clock-setup/ntp                     boolean true

# --- Accounts -------------------------------------------------------------
# The installer only accepts a lowercase login, so the account is created as
# '$installerName'$(if ($needsRename) { " and renamed to '$UserName' in late_command" }).
d-i passwd/root-login                   boolean false
d-i passwd/make-user                    boolean true
d-i passwd/user-fullname                string $display
d-i passwd/username                     string $installerName
d-i passwd/user-password                password $plain
d-i passwd/user-password-again          password $plain
d-i user-setup/allow-password-weak      boolean $weak
d-i user-setup/encrypt-home             boolean false

# --- Partitioning: whole disk, one partition, no LVM ----------------------
d-i partman-auto/method                 string regular
d-i partman-auto/choose_recipe          select atomic
d-i partman-partitioning/confirm_write_new_label boolean true
d-i partman/choose_partition            select finish
d-i partman/confirm                     boolean true
d-i partman/confirm_nooverwrite         boolean true
d-i partman-efi/non_efi_system          boolean true
d-i partman-md/confirm                  boolean true

# --- Packages -------------------------------------------------------------
tasksel tasksel/first                   multiselect
d-i pkgsel/include                      string $packages
d-i pkgsel/upgrade                      select full-upgrade
d-i pkgsel/update-policy                select none
popularity-contest popularity-contest/participate boolean false

# --- Bootloader -----------------------------------------------------------
d-i grub-installer/only_debian          boolean true
d-i grub-installer/with_other_os        boolean false
d-i grub-installer/bootdev              string default

# --- Post-install ---------------------------------------------------------
$lateCommand

d-i finish-install/reboot_in_progress   note
"@

    $plain = $null
    return $text
}

function Write-AutoVMPreseed {
    <#
        .SYNOPSIS
        Writes a preseed into a permission-restricted run directory.

        .OUTPUTS
        The path of the written file. The caller must shred it with
        Remove-AutoVMFileSecurely once the install has consumed it.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$Content,
        [Parameter(Mandatory)][string]$RunDirectory
    )

    if (-not (Test-Path -LiteralPath $RunDirectory)) {
        New-Item -ItemType Directory -Force -Path $RunDirectory | Out-Null
    }
    Protect-AutoVMDirectory -Path $RunDirectory

    $path = Join-Path $RunDirectory 'preseed.cfg'
    # The installer reads this as a plain text file; write LF endings and no BOM.
    $bytes = [System.Text.UTF8Encoding]::new($false).GetBytes(($Content -replace "`r`n", "`n"))
    [System.IO.File]::WriteAllBytes($path, $bytes)

    Write-AutoVMLog -Level Info -Message "Installer answer file written to $path"
    return $path
}
